### ISSUE TITLE
How to install CLI in Mac OS using the downloaded file

### ISSUE THREAD

**Issue by prashanthmadarapu** [Peripli/service-manager-cli#63]
### Step 1: Is this issue for here?

The issue is related to the installation of CLI in Mac OS.

### Step 2: Describe the problem (very short text description):

The downloaded for Mac OS does not have any extension like pkg and I am not sure how to make use of it to install the tool.

**Comment by Madhu2707** [comment]
Hi, So here is what I did to get it installed on my mac. 

1. Give execute permissions to smctl_osx (chmod +x)
2. Copy it to go/bin
3. Try to execute it from command line, if you get an error like mac doesn't trust the developer, right click and open the executable and say open anyway.
4. This should do the installation and thenyou could  rename smctl_osx to smctl

**Comment by tamiarah** [comment]
Hi,

I am experiencing the same issue. Is a fix or any installation details for Mac users planned?

Thanks and best regards,
Christina

**Comment by sfroee** [comment]
Hi experts,

I have mac pro laptop running on Big Sur OS (intel processor)
on the release page there are few options based on darwin, which I guess it's for mac.

But when I try to download and run the smctl from smctl-v1.11.7-darwin-386.tar.gz
I get this error :
```
$ smctl
-bash: /usr/local/bin/smctl: Bad CPU type in executable
```

while the version from smctl-v1.11.7-darwin-amd64.tar.gz
did work.

mac pro is not based on AMD so I think there is some error in the way you release the versions 
perhaps it's causing also other mac users to fail due to it.

Thanks and best regards
Roy

**Comment by alexwo** [comment]
Hi @sfroee, 
"AMD64" is the name chosen by AMD for their 64-bit extension to the Intel x86 instruction set. 
The name of the release is called darwin-amd64 as it refers to the 64bit architecture and a darwin(mac) kernel. 

this is actually how we can compile the source code for mac (GOARCH=amd64) 
```
env GOOS=linux GOARCH=amd64 go build
```
in the future, it will be possible to use arm64 releases instead of amd64. 

https://en.wikipedia.org/wiki/X86-64#History_of_AMD64

please let us know if it make sense.
